City-of-Helsinki/unified-search

graphql/babel.config.js, graphql/package-lock.json, graphql/package.json, graphql/src/__tests__/utils.test.js, graphql/src/datasources/es.ts, graphql/src/index.ts, graphql/src/resolvers/__tests__/resolvers.test.js, graphql/src/resolvers/pageInfoResolver.ts, graphql/src/schemas/query.ts, graphql/src/types.ts, graphql/src/utils.ts
This PR adds support for the `after` and `first` in the `unifiedSearch` query.
These variables have been first defined in the Relay spec. The Relay spec also defines `before` and `last` parameters. These have not been implemented, but they have been included in the API. This allows us to communicate that their omission is intentional.
The `before` and `last` parameters require logic that Elasticsearch does not provide for by default. It's possible to make Elasticsearch react to these parameters in the correct manner, but the approaches, such as flipping result order with sort, will likely prove to be brittle in the long run. Furthermore, they add a lot of complexity considering that the behaviour they implement is not something we currently need.
The `after` parameter is an opaque cursor …
=> US-20 | Support after and first from the Relay connection spec

.github/workflows/staging.yml
US-31 Infra: Scheduled data imports
Every night at 03:00, delete 'location' index and fetch new data to it.
Maximum duration of the job is 5 mins by default, increased to 2 hours.
=> Add cron job for data collection

graphql/src/datasources/es.ts, graphql/src/index.ts, graphql/src/schemas/query.ts, sources/ingest/fetch/location.py
This PR enables the completion suggestion query. It consists of three parts:
1. Amending the definition of the `location` index to include mappings the completion suggester requires
2. Changes to the data harvester script which make it collect and store suggestion data according to the new mappings
3. Adding a new query to the Graphql service which makes a suggestion query to elastic and returns a simplified version of the results
When you have `unified-search` running locally, you can test the auto suggester here: https://codesandbox.io/s/vigilant-chatelet-m1sft?file=/src/SearchForm.js
In general elastic suggesters adopt the following form
```js
suggest: {
suggestion-group: { // an arbitrary name for this suggestion result set
prefix, // The string the suggestion is built based of …
```
=> U-24 | Add auto completion suggestion query

.github/workflows/staging.yml, sources/ingest/fetch/location.py, sources/ingest/management/commands/ingest_data.py, sources/sources/settings.py
Reduce verbosity of harvester logging:
- use debug logging instead of info in most cases
- prevent printing Elasticsearch API URL calls with ES specific logger config
- fix DEBUG env variable handling
- Disable debug logging in staging (similar to prod)
=> Less verbose logging

graphql/src/constants.ts, graphql/src/datasources/es.ts, graphql/src/index.ts, graphql/src/schemas/query.ts, graphql/src/types.ts, graphql/src/utils.ts
This PR changes which index fields are targeted based on the languages the API consumer is requesting.
As a part of this PR, we are changing how "search all" is defined. Instead of targeting all indexed fields ("*"), it now targets the following fields:
```
'venue.name',
'venue.description',
'links.raw_data.short_desc',
```
This change was done in order to tackle the increased amount of maintenance load that language support forced us to add.
To avoid targeting all languages, we have to limit the set of fields we target. We can only do this by "safelisting", i.e. listing all the fields we want to search from.
API consumers can now specify the `languages` parameter while making a `unifiedSearch` query to limit the queried fields to a language or languages.
=> US-23 | GraphQL: results filtering based on language

README.md, graphql/src/index.ts, sources/ingest/fetch/location.py
- Use datetime type for time stamps.
- Fix Hauki URL's to use production version.
- Remove unnecessary JSON + string conversion
- Add example time range query
=> Improve time handling

graphql/src/datasources/es.ts, sources/ingest/fetch/location.py
This PR attempts to improve searches which have the language context. There are two changes.
This PR adds the language analyzer for the venue's language aware fields.
These analyzers help elastic break down words into their unconjugated forms. For instance "Herttoniemi" will then match "Herttoniemen". Without these analyserzs the example would not be a match.
This change will decrease the amount of cases where "should be matches" are not matched due to the language context.
Changes into the query logic disallow such matches, where a match of one type in language A and a match in a second type in language B yield a match. For instance, when the searched string "Herttoniemi" matches an English description (with no other languages matching) and an ontology of "taide" matches a Finnish field …
=> US-23 | Fix searching with language

graphql/src/datasources/es.ts, graphql/src/index.ts, sources/ingest/fetch/event.py, sources/ingest/fetch/keyword.py
Harvester
- Cache Linkedevents keywords locally.
- Store enriched keyword information in raw data.
- Store keywords grouped by language in new high level data structure "ontology". This
is supposed to be general purpose format to be shared between indexes.
GraphQL
- Use ontology fields in query. Event index now uses the general purpose format.
=> Ontology query for event index

.github/workflows/production.yml, .github/workflows/staging.yml, graphql/src/schemas/actor.ts, graphql/src/schemas/location.ts, sources/ingest/fetch/location.py
- Split harvester cron job into index specific jobs, "location" and "event".
- Fix address resolving. Variable names must match exactly on Python and TS side.
- Allow HTTP errors when storing Linkedevents place. In some cases the place is not available or there's NW error. Just skip and continue processing other units.
=> Cron improvements

sources/ingest/fetch/event.py
This also prevents extra query strings in the URL as
meta.next returns query string back and it was then
duplicated in the URL.
=> Fetch data with default page size

.github/workflows/review.yml, .github/workflows/staging.yml, sources/sources/settings.py
Greatly reduce the amount of events fetched. Remove custom Linkedevents URL used for staging event index.
=> Fetch only current events

graphql/src/datasources/es.ts, graphql/src/index.ts
Previously cursors were generated naive of the current offset. This meant that nth cursors on two pages would be identical. For instance, the 2nd cursor would always point to the second result in the result set instead of the second result on a given page.
Now pagination takes pagination offset into account.
https://unified-search-fix-pagination-30-graphql.test.kuva.hel.ninja/search
Query that can be used for testing
```
query {
unifiedSearch(
q: "*"
index: "location"
ontology: "Liikunta"
first: 4
) {
count
pageInfo {
hasNextPage
endCursor
}
edges {
node {
venue {
name {
fi
}
}
}
}
}
}
```
=> Fix incorrect cursors after first page

graphql/src/datasources/es.ts, graphql/src/index.ts, graphql/src/schemas/location.ts, graphql/src/schemas/query.ts, sources/ingest/fetch/location.py
Added administrative divisions:
* `Venues` now have field `location.administrativeDivisions` containing the venue's divisions
* It is possible to filter search results by a division by proving the division's ID in `admistrativeDivision` parameter
* Available divisions for filtering can fetched from the GraphQL API's by querying root level `administrativeDivisions`
Some considerations: 
* The GQL API includes only divisions that exist in the data. We might want to change that to include all of the divisions instead. 
* The list of all existing divisions is stored in its own ES index now, mainly just because that seemed to be the easiest option currently. We might want to change that, maybe even use something else than ES.
=> US-47 | Add administrative divisions

graphql/src/datasources/es.ts, graphql/src/index.ts, graphql/src/schemas/query.ts
Also results linked to the given ontology tree's child tree objects are included.
Example query:
```graphql
query {
unifiedSearch(q: "ranta", index: "location", ontologyTreeId: 551) {
edges {
node {
venue {
name {
fi
}
}
}
}
}
}
```
=> Add ontology tree id filter

graphql/src/index.ts
Coordinates would resolve as `null` for some venues. This change implements a `GeoJSONFeature` resolver which bridges the gap so that the `GeoJSONPoint` resolver gets called when the user asks for coordinates.
I also added some hardcoded definitions for some required type fields.
=> Fix coordinate resolving for tprek venues

graphql/src/datasources/es.ts
Fixed administrative divisions query to return all the divisions. Also changed the request which fetches the divisions from Elastic Search from POST to GET, because it is simpler and there is no need for a POST request.
=> US-51 | Fix administrative divisions query to return all

graphql/src/datasources/es.ts, graphql/src/index.ts, graphql/src/schemas/query.ts
Added filters `administrativeDivisionIds` and `ontologyTreeIds` which allow filtering search results by multiple values which are ORred.
=> US-56 & US-57 | Allow filtering by multiple divisions and ontology trees

graphql/src/datasources/es.ts, graphql/src/index.ts, graphql/src/schemas/query.ts
Adds the `ontologyWordIds` filter into the `unifiedSearch` query.
Ontologies are sourced from tprek and matched with the same logic as ontology tree ids.
=> US-66 | Add filtering based on ontology word ids

.github/workflows/production.yml, .github/workflows/staging.yml
We have the new fancy double index and alias system to provide transactional ingest runs, we don't want no index deletion before ingesting data no more!
=> Fix ingest cronjobs

graphql/package.json, graphql/src/datasources/es.ts, graphql/src/index.ts, graphql/src/schemas/location.ts, graphql/src/schemas/query.ts, sources/ingest/importers/location.py, sources/ingest/importers/utils/opening_hours.py, sources/ingest/importers/utils/tests/snapshots/snap_test_opening_hours.py, sources/ingest/importers/utils/tests/test_opening_hours.py
Implemented search query `openAt` filter for venues, which limits the results to venues that are open at the given time.
The filter accepts ISO 8601 datetimes with and without a timezone offset (if there is no offset given, the datetime is assumed to be in timezone "Europe/Helsinki") and values conforming to Elastic Search date math, like "now+3h".
The make implementing the filter possible, all venues' open hours are indexed as ranges of datetimes when the venues are open. The ranges are built based on Hauki's `"resource_state"` `"open"` time ranges which are overridden by `"resource_state"` `"closed"` ranges.
This PR also includes a change that opening hours of the next 7 days are imported instead of the previous value of 1, and all of those opening hours are now exposed via the GraphQL …
=> US-61 & US-62 | Search query "open at" filter

graphql/src/datasources/es.ts, graphql/src/index.ts, graphql/src/schemas/query.ts, sources/ingest/importers/location.py
Added argument
orderByDistance: {latitude: Float, longitude: Float, order: SortOrder = ASCENDING}
to the search query, which allows sorting the results by their distance to the given point, by default nearest first.
Venues' coordinates are indexed as a separate `geo_point` to support this.
Example query:
```graphql
query {
unifiedSearch(q: "uimahalli", index: "location", orderByDistance: {latitude: 24.937, longitude: 60.163}) {
edges {
node {
venue {
name {
fi
}
}
}
}
}
}
```
=> US-63 | Allow sorting search results by distance

graphql/src/datasources/es.ts, graphql/src/index.ts, graphql/src/schemas/query.ts, sources/ingest/importers/location.py
Created a set of Helsinki administrative divisions that can be used in a UI as division choices. They are put in their own index for easier usage. Added argument `helsinkiCommonOnly` which can be used to fetch those from the GraphQL API.
**NOTE**: There are many fuzzy factors about this thing, starting from the question that should this even be in Unified Search in the first place, so this implementation is subject to change in the future.
Example query:
```graphql
query {
administrativeDivisions(helsinkiCommonOnly: true) {
type
name {
fi
}
}
}
```
=> US-64 |  Helsinki common administrative divisions

docker-compose.yml
`unless-stopped` is similar to `always` flag, but it doesn't restart any stopped containers when the Docker daemon restarts (e.g. on system boot).
https://docs.docker.com/config/containers/start-containers-automatically/#use-a-restart-policy
=> Prevent stopped docker-compose containers restarting on boot

sources/ingest/apps.py, sources/requirements.in, sources/requirements.txt, sources/sources/settings.py
US-87. Downgraded the elasticsearch library to fix the server is not a supported distribution of Elasticsearch -error: https://towardsaws.com/elasticsearch-the-server-is-not-a-supported-distribution-of-elasticsearch-252abc1bd92. Also set the default AutoField setting, because current version of munigeo does not set it.
=> Fixed the UnsupportedProductError

.github/workflows/production.yml, .github/workflows/staging.yml
This PR makes the cronjobs started from the pipeline to stop executing (progressing to the next command) if there's a failure. Previously the next command was run even though the previous command failed.
=> US-90 | Cronjob should immediately stop when there's a failure

graphql/src/datasources/es.ts, graphql/src/resolvers/pageInfoResolver.ts
US-83. Before the fix, hasNextPage was always `false`, if the first -argument was not given.
Test query:
```
{
unifiedSearch(
q: "*"
) {
count
pageInfo {
hasNextPage
hasPreviousPage
}
edges {
node {
venue {
name {
fi
}
}
}
}
}
}
```
=> Use a default page size value with the hasNextPage when a first argument is not given

graphql/Dockerfile, graphql/package.json, graphql/src/index.ts, graphql/src/schemas/actor.ts, graphql/src/schemas/es.ts, graphql/src/schemas/event.ts, graphql/src/schemas/geojson.ts, graphql/src/schemas/linkedevents.ts, graphql/src/schemas/location.ts, graphql/src/schemas/ontology.ts, graphql/src/schemas/palvelukartta.ts, graphql/src/schemas/query.ts, graphql/src/schemas/reservation.ts, graphql/src/schemas/shared.ts, graphql/yarn.lock
The subgraph requirements (https://www.apollographql.com/docs/federation/subgraph-spec/) must be met in the graph that the Apollo-server serves.
1. Upgrade all the Apollo dependencies to the latest.
2. Change the old way of schema creation from `mergeSchemas({ schemas: typeDefs, resolvers })` to `buildSubgraphSchema({ typeDefs, resolvers })`. This is “a function that takes a schema module object (or an array of them) and returns a federation-ready subgraph schema”.
3. Add a new Federation 2 directive to the root Query:
```
export const Query = gql`
extend schema @link(url: "https://specs.apollo.dev/federation/v2.0", import: ["@key", "@shareable"])
type Query {
_empty: String
}
`;
```
4. The Keyword type and the Location Image type were overlapping with Events-Helsinki-proxy …
=> Upgrade the Apollo server related dependencies and migrate the monolith graph to a new subgraph

sources/Dockerfile
Cronjobs are run with django and it needs to initialize empty local database even the database is not used.
=> Openshift write access to sources -image app directory for local db file

graphql/src/schemas/location.ts, sources/ingest/importers/location.py, sources/ingest/importers/tests/test_accessibility_sentences.py, sources/ingest/importers/tests/test_accessibility_shortages.py
`python manage.py ingest_data location` will now import venues'
accessibility shortages per viewpoint:
- List of accessibility shortages (fi/sv/en) for each accessibility
viewpoint, e.g.
- Viewpoint "I am a rollator user - arrive by my car" (id="32"):
- Shortages (With translations into Finnish and Swedish):
- "No parking places for persons with a disability."
- "The entrance has a cramped foyer."
refs US-103
`python manage.py ingest_data location` will now import venues'
accessibility sentences:
- List of accessibility sentences each containing:
- sentence group name
- sentence group (fi/sv/en)
- sentence (fi/sv/en)
refs US-103
- [US-103](https://helsinkisolutionoffice.atlassian.net/browse/US-103)
- checkout this PR's branch's version
- `cp .env.example .env`
- `docker-compose up …
=> US-103 | import venues' accessibility shortages and sentences

graphql/src/schemas/location.ts, sources/ingest/importers/location.py, sources/ingest/importers/tests/test_target_groups.py
`python manage.py ingest_data location` will now import venues' target
groups from service description registry (palvelukuvausrekisteri in
Finnish).
A single venue can belong to zero or more of these target groups:
- ASSOCIATIONS
- CHILDREN_AND_FAMILIES
- DISABLED
- ELDERLY_PEOPLE
- ENTERPRISES
- IMMIGRANTS
- INDIVIDUALS
- YOUTH
refs US-109
- [US-109](https://helsinkisolutionoffice.atlassian.net/browse/US-109)
- checkout this PR's branch's version
- `cp .env.example .env`
- `docker-compose up --build`
- `docker exec -it unified-search_sources_1 bash`
- `python manage.py ingest_data location --use-fallback-languages`
- Open http://localhost:5601/app/dev_tools#/console and fetch data [1]
[1] fetch data:
```
GET _search
{
"query": {
"match_all": {}
}
}
```
Fetched data for unit 28414:
``` …
```
=> US-109 | feat: import venues' target groups from service description registry

sources/ingest/importers/base.py, sources/ingest/management/commands/ingest_data.py
Switch from
- not using fallback languages by default
- providing an option to use them with --use-fallback-languages
to
- using fallback languages by default
- providing an option to not use them with --ignore-fallback-languages
refs US-100
[US-100](https://helsinkisolutionoffice.atlassian.net/browse/US-100)
[US-100]: https://helsinkisolutionoffice.atlassian.net/browse/US-100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> US-100 | feat(ingest_data): use fallback languages (Order: fi, en, sv) by default

graphql/src/datasources/es.ts, graphql/src/index.ts, graphql/src/schemas/query.ts, sources/ingest/importers/location.py, sources/ingest/importers/tests/test_resources.py
Add GraphQL inputs and filter using them:
- providerTypes: [ProviderType]
- Optional, filter to match any of these provider types
- serviceOwnerTypes: [ServiceOwnerType]
- Optional, filter to match any of these service owner types
- targetGroups: [TargetGroup]
- Optional, filter to match any of these target groups
- mustHaveReservableResource: Boolean
- Optional, filter to show only venues that have at least one
reservable resource. If not given or false, all venues are shown.
- accessibilityProfilesWithoutShortcomings: [AccessibilityProfile]
- Optional, filter to show only venues that have no known
shortcomings for any of the given accessibility profiles.
refs US-103 (accessibilityProfilesWithoutShortcomings filter)
refs US-107 (providerTypes and serviceOwnerTypes filters)
refs US-108 …
=> US-103, US-107, US-108, US-109 | feat: add GraphQL filters for serviceOwnerTypes, targetGroups etc

graphql/src/schemas/location.ts, graphql/src/schemas/query.ts, graphql/src/schemas/shared.ts
City-of-Helsinki/unified-search GraphQL schema is used as a subgraph in
City-of-Helsinki/events-helsinki-monorepo project's
events-graphql-federation supergraph. There are changes done directly
into the subgraph without having done them into unified search's
schemas, see
/proxies/events-graphql-federation/subgraphs/unified-search/README.md:
> WARNING: There is conflict with the Venue type, so it's renamed in
> supergraph, but not yet deployed in the actual server.
Sync those changes from events-helsinki-monorepo repository's
events-helsinki-graphql-federation's unified-search.graphql subgraph
back into this repository.
refs US-109 (trying to test this with events-helsinki-monorepo)
[US-109](https://helsinkisolutionoffice.atlassian.net/browse/US-109) (trying to test this with …
=> US-109 | fix(graphql): rename Venue to UnifiedSearchVenue & sync schema comments

graphql/src/index.ts
refs US-109 (renamed Venue to UnifiedSearchVenue in PR #104)
[US-109](https://helsinkisolutionoffice.atlassian.net/browse/US-109)
[US-109]: https://helsinkisolutionoffice.atlassian.net/browse/US-109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> US-109 | fix(graphql): fix resolving of UnifiedSearchVenue type after rename

sources/ingest/importers/utils/language.py, sources/ingest/management/commands/ingest_data.py, sources/ingest/tests/test_language.py
refs US-111 (changing fallback language order to en/fi/sv)
refs HH-110 (the original fallback languages order defined)
refs LIIKUNTA-547 (City-of-Helsinki/events-helsinki-monorepo#420 used fallback language order en/fi/sv)
- [US-111](https://helsinkisolutionoffice.atlassian.net/browse/US-111)
- [HH-110](https://helsinkisolutionoffice.atlassian.net/browse/HH-110)
- [LIIKUNTA-547](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-547)
[US-111]: https://helsinkisolutionoffice.atlassian.net/browse/US-111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HH-110]: https://helsinkisolutionoffice.atlassian.net/browse/HH-110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIIKUNTA-547]: …
=> US-111 | fix: change fallback language order from fi/en/sv to en/fi/sv

graphql/src/datasources/es.ts, graphql/src/index.ts, graphql/src/schemas/query.ts
ontologyTreeIdsOrSet2 query parameter:
- "Optional, filter to match only these ontology tree ids,
if ontologyTreeIds is also given then it must match separately i.e.
at least one ontology tree ID must match in both sets separately."
refs LIIKUNTA-27
[LIIKUNTA-27](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-27)
- check out PR's branch
- `docker compose up --build`
- `docker exec -it unified-search-sources-1 bash`
- `python manage.py ingest_data location`
- Wait 5-10mins for location data import to finish
- query local http://localhost:4000/search GraphQL endpoint with e.g. query for ontology tree IDs 611 and 2221 matching separately
<summary>query for ontology tree IDs 611 and 2221 matching separately</summary>
<details>
```graphql
query unifiedSearch {
unifiedSearch( …
```
=> LIIKUNTA-27 | feat(graphql): add ontologyTreeIdsOrSet2 query parameter

graphql/src/schemas/location.ts, sources/ingest/importers/location.py, sources/ingest/importers/tests/test_fix_unknown_and_zero_shortcomings.py, sources/ingest/importers/utils/shared.py, sources/ingest/tests/test_language.py
refs US-112
[US-112](https://helsinkisolutionoffice.atlassian.net/browse/US-112)
Set up data locally:
- `docker compose up --build`
- `docker exec -it unified-search-sources-1 bash`
- `python manage.py ingest_data location`
Opened http://localhost:4000/search in Insomnia and queried with:
<summary>GraphQL query</summary>
<details>
```graphql
query unifiedSearch {
unifiedSearch(
index: "location"
q: "Kaunokki"
languages: [FINNISH]) {
edges {
cursor
node {
venue {
meta {
id
}
name {
fi
}
accessibility {
viewpoints {
id
value
name {
fi
}
shortages {
fi
}
}
shortcomings {
profile
count
}
}
}
}
}
}
}
```
</details>
<summary>Results</summary>
<details>
```json
{
"data": {
"unifiedSearch": {
"edges": [{
"cursor": "eyJvZmZzZXQiOjF9",
"node": {
"venue": {
"meta": {
"id": "5"
},
"name": {
"fi": …
```
=> US-112 | fix: fix unknown and zero accessibility shortcoming counts

azure-pipelines-unified-search-sources-review.yml, azure-pipelines-unified-search-sources-test.yml
left the commented out URLs for LinkedEvents test environment in
the pipeline files if there's a need to test against the test
environment, alternatively they could be removed completely for clarity
=> fix: fix broken LinkedEvents URLs in review and testing environments

graphql/package.json, graphql/src/datasources/es.ts, graphql/src/index.ts, graphql/src/schemas/query.ts
also:
- add "typecheck" command to graphql package.json for checking
Typescript types
- add more typings to the use of indices
refs US-115
[US-115](https://helsinkisolutionoffice.atlassian.net/browse/US-115)
[US-115]: https://helsinkisolutionoffice.atlassian.net/browse/US-115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> US-115 | feat(graphql): type graphql search index with an enumeration for clarity

graphql/src/datasources/es/api/getQueryResults/constants.ts, graphql/src/datasources/es/api/getQueryResults/getQueryResults.ts, graphql/src/datasources/es/api/getQueryResults/types.ts, graphql/src/datasources/es/api/getQueryResults/utils/getDefaultQuery.ts, graphql/src/datasources/es/api/getQueryResults/utils/getOntologyQuery.ts, graphql/src/datasources/es/api/getQueryResults/utils/index.ts, graphql/src/types.ts
US-123
Use bool-query with `match_bool_prefix` and `match_phrase` instead of `query_string` query.
Add a bool-query to replace the query_string-query,
since it is simpler and does not need any special care for input.
Add a `match_phrase` query on side of `match_bool_prefix`
to give higher score for "exact matches".
Add a new query function on besides of the old 
`query_string` implementation, just to make the future development easier, if we go back to query string.
Example (tested): When searching with a text-parameter set as 
"Itäkeskuksen uimahalli / Kuntosali",  it returns 
the exact match as first. The result set is a following 
(only name fields included):
1. Itäkeskuksen uimahalli / Kuntosali
2. Itäkeskuksen uimahalli
3. Itäkeskuksen uimahalli / Liikuntasali
4. Itäkeskuksen …
=> Exact matches should be higher in relevance

graphql/src/datasources/es/api/getQueryResults/utils/getDefaultQuery.ts, graphql/src/datasources/es/api/getQueryResults/utils/getOntologyFields.ts, graphql/src/datasources/es/api/getQueryResults/utils/getOntologyQuery.ts
US-124.
Search also from the ontologies when using
the default text search query for locations.
=> feat(graphql): include ontologies in default search query

sources/.pre-commit-config.yaml, sources/ingest/importers/location/tests/test_location_importer_basics.py, sources/ingest/importers/location/tests/test_reservable.py, sources/requirements-dev.txt, sources/setup.cfg
US-126 US-128.
First quick fix to this issue that some tests fails,
because they need an ElasticSearch connection,
is to disable those tests in CI-pipeline.
=> test(sources): ignore tests on CI-pipeline that rely on ES-connection

graphql/src/index.ts
US-119 US-132. Added the missing environment agument in Sentry init configuration
=> feat(graphql): add Sentry environment argument to configuration

sources/ingest/importers/location/utils.py
Remove incorrect deprecation of `get_unit_id_to_accessibility_sentences_mapping` function from `/sources/`.
Previously get_unit_id_to_accessibility_sentences_mapping was deprecated based on the idea that accessibility sentences for a unit can be fetched using LocationImporterAPI.fetch_tpr_units function.
Looking at that function it fetches data from
https://www.hel.fi/palvelukarttaws/rest/v4/unit/?newfeatures=yes which DOES NOT include accessibility sentences.
The deprecation text referred to a single unit's fetching e.g. https://www.hel.fi/palvelukarttaws/rest/v4/unit/42284?official=yes&format=json&newfeatures=yes which DOES include accessibility sentences for that unit but it is not the URL that is being used by LocationImporterAPI.fetch_tpr_units. Thus, the deprecation was based on …
=> US-174 | Fix `/sources/` related deprecations

graphql/Dockerfile
EXPOSE port 4000 in graphql's Dockerfile
[US-120](https://helsinkisolutionoffice.atlassian.net/browse/US-120)
[US-120]: https://helsinkisolutionoffice.atlassian.net/browse/US-120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> US-120 | EXPOSE port 4000 in graphql's Dockerfile

graphql/src/readiness.ts
Use better workaround for graphql app's build time.
Similarly as in sources app's settings.py a file's modification time
is used as a workaround for approximating readiness endpoint's
build time. This is not foolproof, but better than nothing—the previous
way of using the file's evaluation time was probably more problematic
than this as it probably would've changed if the pod got respawned.
[US-151](https://helsinkisolutionoffice.atlassian.net/browse/US-151)
[US-151]: https://helsinkisolutionoffice.atlassian.net/browse/US-151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> US-151 | Use better workaround for graphql app's build time

sources/sources/csp_settings.py, sources/tests/test_csp.py
Remove upgrade-insecure-requests CSP directive from sources app as unneeded.
[US-177](https://helsinkisolutionoffice.atlassian.net/browse/US-177)
[US-177]: https://helsinkisolutionoffice.atlassian.net/browse/US-177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> US-177 | Remove upgrade-insecure-requests CSP directive from sources app as unneeded

.env.example, graphql/src/index.ts, graphql/src/schemas/location.ts, graphql/src/schemas/query.ts, sources/openapi.yaml
Add Apollo Sandbox support,
can be enabled with `ENABLE_APOLLO_SANDBOX=1` in
`.env` at least when run with Docker Compose locally.
- [US-181](https://helsinkisolutionoffice.atlassian.net/browse/US-181)
- [Related DevOps pipeline changes](https://dev.azure.com/City-of-Helsinki/kuva-unified-search/_git/kuva-unified-search-pipelines/pullrequest/12028)
[US-181]: https://helsinkisolutionoffice.atlassian.net/browse/US-181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> US-181 | Add Apollo Sandbox support

README.md, sources/ingest/importers/base.py, sources/ingest/management/commands/ingest_data.py
The support for deleting data using `ingest_data` management
command was broken (specifically location importer didn't just
delete data when asked to but it ALSO imported data even when
it shouldn't have), and is not used in Azure DevOps, so it can be
safely removed.
This is simplifying the codebase by removing broken functionality
that "might be useful" in a sense, but probably isn't *really* needed.
[US-185](https://helsinkisolutionoffice.atlassian.net/browse/US-185)
[US-185]: https://helsinkisolutionoffice.atlassian.net/browse/US-185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> US-185 | Remove support for `ingest_data` data deletion as unneeded

.github/workflows/ci-graphql.yml
Enable typechecking of graphql project in github actions.
[US-183](https://helsinkisolutionoffice.atlassian.net/browse/US-183)
[US-183]: https://helsinkisolutionoffice.atlassian.net/browse/US-183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> US-183 | Enable typechecking of graphql project in github actions

README.md, graphql/Dockerfile, graphql/README.md, graphql/package.json, graphql/src/datasources/es/api/getQueryResults/constants.ts, sources/README.md, sources/openapi.yaml
Update READMEs:
- add information to README about why OpenSearch is used
- document search weighting factors in README
- add development environments to READMEs
- add more info about how to set up pre-commit hooks successfully
Also:
- change vocabulary & scripts from using transpile → build
[US-183](https://helsinkisolutionoffice.atlassian.net/browse/US-183)
[US-183]: https://helsinkisolutionoffice.atlassian.net/browse/US-183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> US-183 | Update READMEs

graphql/README.md, sources/README.md
Add endpoint documentation links to READMEs.
[US-181](https://helsinkisolutionoffice.atlassian.net/browse/US-181)
[US-181]: https://helsinkisolutionoffice.atlassian.net/browse/US-181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> US-181 | Add endpoint documentation links to READMEs

.env.example, .github/workflows/ci-sources.yml, README.md, compose.yaml, graphql/README.md, graphql/src/datasources/es/constants.ts, sources/ingest/importers/base.py, sources/ingest/importers/location/dataclasses.py, sources/ingest/importers/tests/conftest.py, sources/ingest/importers/tests/snapshots/snap_test_base_importer.py, sources/ingest/importers/tests/test_base_importer.py, sources/requirements.in, sources/requirements.txt, sources/tests/test_es_health.py
Switch from OpenSearch → ElasticSearch & Kibana v9.1.3.
See commit messages for more details.
https://www.elastic.co/blog/elasticsearch-is-open-source-again (August 2024):
> The tl;dr is that we will be adding AGPL as another license option next to ELv2 and SSPL in the coming weeks. 
https://www.elastic.co/pricing/faq/licensing (September 2025):
> In September 2024, we are adding the Open Source Initiative (OSI) approved AGPLv3 license as an option alongside SSPL and our Elastic license ensuring our community and customers have open source access to use, modify, redistribute, and collaborate on the code with a clear set of rights of their choice. Our releases will continue to be under the Elastic License.
https://www.elastic.co/licensing/elastic-license/faq:
> Can you summarize what is …
=> US-194 | Switch to Elasticsearch

README.md
Document Headless CMS's use of unified search more in depth.
- [US-195](https://helsinkisolutionoffice.atlassian.net/browse/US-195)
- https://github.com/devgeniem/hkih-sportslocations
- Headless CMS code for "Sports Locations" and "Sports Locations carousel" modules
[US-195]: https://helsinkisolutionoffice.atlassian.net/browse/US-195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> US-195 | Document Headless CMS's use of unified search more in depth
