graphql/src/datasources/es.ts
graphql/src/index.ts
graphql/src/schemas/query.ts

US-22 GraphQL: filtering based on categories

Initial support for category filtering

---

sources/ingest/fetch/location.py
sources/ingest/fetch/ontology.py
sources/ingest/fetch/traffic.py

Fetch full ontology tree and ids and cache them locally instead
of requesting ids separately from API.

Fetch full ontology tree

---

graphql/src/datasources/es.ts

This search includes only hits with matching (optional) ontology.

Use multimatch for ontology categories

---

.github/workflows/staging.yml

Cron was run in matrix creating unnecessary duplicated job.
Fixed also image name.

Improve cron job

---

.env.example
.github/workflows/production.yml
.github/workflows/staging.yml
README.md
graphql/babel.config.js
graphql/package-lock.json
graphql/package.json
graphql/src/__tests__/utils.test.js
graphql/src/datasources/es.ts
graphql/src/index.ts
graphql/src/resolvers/__tests__/resolvers.test.js
graphql/src/resolvers/pageInfoResolver.ts
graphql/src/schemas/query.ts
graphql/src/types.ts
graphql/src/utils.ts
sources/ingest/fetch/location.py
sources/ingest/fetch/ontology.py
sources/ingest/fetch/traffic.py
sources/ingest/fetch/vapaaehtoistoiminta.py
sources/ingest/management/commands/ingest_data.py
sources/sources/settings.py

Merge develop to main

---

.github/workflows/review.yml
.github/workflows/staging.yml
graphql/src/index.ts

Also provide GraphQL playground in staging.

Enable introspection

---

.github/workflows/production.yml
.github/workflows/staging.yml
README.md

Harvest event index data in cron jobs.
Improve README.

Event index cron job

---

sources/ingest/importers/base.py
sources/ingest/importers/event.py
sources/ingest/importers/location.py
sources/ingest/importers/ontology_tree.py
sources/ingest/importers/tests/snapshots/snap_test_base_importer.py
sources/ingest/importers/tests/test_base_importer.py
sources/ingest/management/commands/ingest_data.py

Implemented zero downtime re-indexing using two actual ES indexes which are used in turns, and an index alias that points to the index that contains the latest complete data. When an import finishes, the alias is swapped to point to the newly finished index.
Although this seemed like a pretty simple thing to do, the implementation actually got stupidly complex. On a positive note, the whole thing is handled inside the base importer, so importers using it should not need to care about that.

US-58 | Implement zero downtime re-indexing

---

graphql/src/datasources/es.ts

US-63 | Fix ordering results by distance

---

.github/workflows/production.yml
.github/workflows/staging.yml
README.md
graphql/src/datasources/es.ts
graphql/src/index.ts
graphql/src/schemas/query.ts
graphql/src/types.ts
sources/ingest/importers/__init__.py
sources/ingest/importers/ontology_word.py
sources/ingest/importers/ontology_words.py
sources/ingest/management/commands/ingest_data.py

- Add ontology_words index to elasticsearch
- Add graphql query for fetching ontology words by ids
**[US-73](https://helsinkisolutionoffice.atlassian.net/browse/US-73):**

US-73 | Add ontology_words index and apollo query

---

sources/ingest/importers/location.py

Before this fix duplicate areas could end up indexed if the sub district of the duplicate was encountered before the neighborhood. Also while at it, replaced the whole common area import logic with (hopefully) a bit less cryptic version.

US-64 | Fix Helsinki common areas import

---

docker-compose.yml
graphql/src/datasources/es.ts

US-54: Add weights for locations to have better scores in searches. 
"Add weight/boost to the fields at least by making title x times more relevant than description and other fields. Try for example with x=3."

Venue name boosted in default query results

---

docker-compose.yml

This reverts commit 92aee7d293dde19c611050f28955cf15986ddbb1.

Revert "Installed enterprise search app to the Elastic docker environment"

---

sources/ingest/importers/base.py
sources/ingest/importers/tests/test_base_importer.py
sources/requirements.in
sources/requirements.txt
test/test_es_health.py
test/test_es_search.py

Replaced the Elasticsearch library with the Opensearch lib

---

.github/workflows/production.yml

Production deployment should be triggered only with release tags

---

.github/workflows/production.yml
.github/workflows/staging.yml

Add APP_MIGRATE_COMMAND only to Sources context

---

graphql/Dockerfile
sources/Dockerfile

[DEVOPS-483](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-483)
[DEVOPS-483]: https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Openshift build fixes

---

azure-pipelines-unified-search-sources-test.yml
sources/ingest/importers/base.py

Platta elastic search connection timeout error

---

azure-pipelines-unified-search-sources-review.yml
azure-pipelines-unified-search-sources-test.yml
sources/Dockerfile

[DEVOPS-543](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-543)
[DEVOPS-543]: https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

build: test and review environments events url to linked events staging

---

graphql/src/schemas/location.ts
sources/ingest/importers/location.py
sources/ingest/importers/tests/test_accessibility_viewpoints.py

`python manage.py ingest_data location` will now import venues'
- provider type (e.g. "SELF_PRODUCED")
- displayed service owner type (e.g. "MUNICIPAL_SERVICE")
- displayed service owner
- accessibility viewpoints
- accessibility www
- accessibility email
- accessibility phone
add test_accessibility_viewpoints.py:
- add tests for accessibility viewpoint helper functions used in
location importer
refs US-103 (accessibility info)
refs US-107 (service provider/owner info)
- [US-103](https://helsinkisolutionoffice.atlassian.net/browse/US-103)
- [US-107](https://helsinkisolutionoffice.atlassian.net/browse/US-107)
- For testing purposes disregard expired certificate of geoserver.hel.fi so testing is possible (→[PT-4958](https://helsinkisolutionoffice.atlassian.net/browse/PLATTA-4985))
- `cp …

US-103, US-107 | feat: import venues' accessibility info and service provider/owner info

---

graphql/src/index.ts
sources/ingest/importers/location.py
sources/ingest/importers/tests/test_resources.py

- fix importing of Respa resources by removing "tprek:" prefix from the unit IDs
- show new data in GraphQL by resolving the added fields
- venue.accessibility related to:
- PR #95
- PR #98
- PR #99
- venue.serviceOwner related to:
- PR #95
- venue.resources related to:
- PR #97
- venue.targetGroups related to:
- PR #100
refs US-103 (showing accessibility information in GraphQL)
refs US-107 (showing service owner related information in GraphQL)
refs US-108 (fixing importing of resources from Respa API)
refs US-109 (showing target groups in GraphQL)
- [US-103](https://helsinkisolutionoffice.atlassian.net/browse/US-103) (showing accessibility information in GraphQL)
- [US-107](https://helsinkisolutionoffice.atlassian.net/browse/US-107) (showing service owner related information in GraphQL) …

US-103, US-107, US-108, US-109 | fix: fix importing of Respa resources & showing new data in GraphQL

---

graphql/src/datasources/es.ts
graphql/src/index.ts
graphql/src/schemas/location.ts
graphql/src/schemas/query.ts
sources/ingest/importers/location.py
sources/ingest/importers/tests/test_fix_unknown_and_zero_shortcomings.py
sources/ingest/importers/utils/shared.py
sources/ingest/tests/test_language.py

Depends on PR #107 
remove:
- accessibilityProfilesWithoutShortcomings query parameter as
unnecessary
add:
- `orderByAccessibilityProfile` query parameter to primarily order by
given accessibility profile's shortcoming count and secondarily by
venue name
- e.g. by "rollator" profile's shortcoming count, first the venues
with no shortcomings at all for rollator, then the ones with 1
shortcoming, 2 shortcomings, ..., N shortcomings and last the ones
with unknown shortcomings for rollator (i.e. no data for/against)
- secondary ordering by venue name is to make the ordering
predictable for venues with same shortcoming count
- `orderedByAccessibilityShortcoming(profile: AccessibilityProfile)`
field to UnifiedSearchVenue type
- Returns the AccessibilityShortcoming object of the given …

US-113 | feat(graphql): order by accessibility profile's shortcoming count

---

graphql/package.json
graphql/src/__tests__/utils.test.js
graphql/yarn.lock

refs LIIKUNTA-255
[LIIKUNTA-255](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-255)
[LIIKUNTA-255]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIIKUNTA-255 | test: add test for escapeQuery

---

graphql/tsconfig.json

fix: transpiling did not include index.js in the dist-root

---

sources/ingest/importers/location/importers.py

fix: location importer Address import

---

graphql/src/datasources/es/index.ts
sources/ingest/importers/location/importers.py

Critical fixes to the location importer

---

graphql/src/datasources/es/api/getQueryResults/index.ts

fix: typescript error

---

LICENSE

Update LICENSE year 2021 → 2025
Related:
- https://helsinkisolutionoffice.atlassian.net/browse/US-180

US-180 | Update LICENSE year 2021 → 2025

---

.github/dependabot.yml

Add .github/dependabot.yml to configure dependabot.
[US-167](https://helsinkisolutionoffice.atlassian.net/browse/US-167)
[US-167]: https://helsinkisolutionoffice.atlassian.net/browse/US-167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

US-167 | Configure dependabot

---

graphql/src/healthz.ts
graphql/src/index.ts
graphql/src/readiness.ts
graphql/tsconfig.json

Add more comprehensive readiness & healthz endpoints to graphql app.
[US-151](https://helsinkisolutionoffice.atlassian.net/browse/US-151)
[US-151]: https://helsinkisolutionoffice.atlassian.net/browse/US-151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

US-151 | Add more comprehensive readiness & healthz endpoints to graphql app

---

sources/requirements-dev.txt
sources/requirements.in
sources/requirements.txt
sources/sources/csp_settings.py
sources/sources/settings.py
sources/tests/test_csp.py

Add CSP to sources app
[US-177](https://helsinkisolutionoffice.atlassian.net/browse/US-177)
[US-177]: https://helsinkisolutionoffice.atlassian.net/browse/US-177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

US-177 | Add CSP to sources app

---

sources/openapi.yaml
sources/tests/test_url_patterns.py

Add openapi.yaml documentation of sources app's available endpoints.
[US-181](https://helsinkisolutionoffice.atlassian.net/browse/US-181)
[US-181]: https://helsinkisolutionoffice.atlassian.net/browse/US-181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

US-181 | Add openapi.yaml documentation of sources app's available endpoints

---

.pre-commit-config.yaml
README.md
graphql/README.md
sources/README.md
sources/ingest/README.md

Update README files.
[US-183](https://helsinkisolutionoffice.atlassian.net/browse/US-183)
[US-183]: https://helsinkisolutionoffice.atlassian.net/browse/US-183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

US-183 | Update README files

---

graphql/README.md
graphql/package.json
graphql/src/index.ts
graphql/src/utils.ts
graphql/vitest.config.ts
graphql/yarn.lock
sources/requirements.in
sources/requirements.txt
sources/sources/settings.py

Load environment variables from `.env` file.
[US-192](https://helsinkisolutionoffice.atlassian.net/browse/US-192)
[US-192]: https://helsinkisolutionoffice.atlassian.net/browse/US-192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

US-192 | Load environment variables from `.env` file

---

.github/workflows/ci-graphql.yml
.github/workflows/ci-sources.yml
graphql/package.json
graphql/sonar-project.properties
sources/ingest/importers/location/tests/test_location_importer_basics.py
sources/ingest/importers/location/tests/test_reservable.py
sources/ingest/importers/tests/test_base_importer.py
sources/sonar-project.properties
sources/tests/test_es_health.py

Refactor pipelines: trasfer tests to Github
[PLATTA-6228](https://helsinkisolutionoffice.atlassian.net/browse/PLATTA-6228)
[PLATTA-6228]: https://helsinkisolutionoffice.atlassian.net/browse/PLATTA-6228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

build: ci workflows PLATTA-6228

---

graphql/src/datasources/es/index.ts
graphql/src/datasources/es/types.ts
graphql/src/resolvers/pageInfoResolver.ts
graphql/src/resolvers/query/administrativeDivisionsResolver.ts
graphql/src/resolvers/query/ontologyTreeResolver.ts
graphql/src/resolvers/query/ontologyWordsResolver.ts
graphql/src/resolvers/query/unifiedSearchCompletionSuggestionsResolver.ts
graphql/src/resolvers/query/unifiedSearchResolver.ts

Fix cyclic import related to QueryContext type
[US-171](https://helsinkisolutionoffice.atlassian.net/browse/US-171)
[US-171]: https://helsinkisolutionoffice.atlassian.net/browse/US-171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

US-171 | Fix cyclic import related to QueryContext type

---

.pre-commit-config.yaml
graphql/package.json
graphql/yarn.lock
sources/requirements-dev.txt
sources/requirements.txt

Update all packages to latest except @types/node to latest v22.
[US-165](https://helsinkisolutionoffice.atlassian.net/browse/US-165) (both sources & graphql projects)
[US-165]: https://helsinkisolutionoffice.atlassian.net/browse/US-165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

US-165 | Update all packages to latest except @types/node to latest v22

---

README.md

Document known users of unified search
[US-195](https://helsinkisolutionoffice.atlassian.net/browse/US-195)
[US-195]: https://helsinkisolutionoffice.atlassian.net/browse/US-195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

US-195 | Document known users of unified search
